tasks:
  - init: mvn install spring-boot:start spring-boot:stop
    command: mvn spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview
  - port: 9001
    onOpen: ignore

vscode:
  extensions:
    - runem.lit-plugin
